In [1]:
import pandas as pd
import numpy as np
import warnings 
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('movies_metadata.csv')
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [3]:
df.columns,df.shape

(Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
        'imdb_id', 'original_language', 'original_title', 'overview',
        'popularity', 'poster_path', 'production_companies',
        'production_countries', 'release_date', 'revenue', 'runtime',
        'spoken_languages', 'status', 'tagline', 'title', 'video',
        'vote_average', 'vote_count'],
       dtype='object'),
 (45466, 24))

In [4]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [5]:
df=df.drop_duplicates().reset_index(drop=True)

In [6]:
df=df[['title','genres','overview','tagline','vote_average','popularity']]

In [7]:
df.head()

,title,genres,overview,tagline,vote_average,popularity
0,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","Led by Woody, Andy's toys live happily in his ...",NaN,7.7,21.946943
1,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,"[{'id': 35, 'name': 'Comedy'}]",Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [8]:
df=df.dropna(subset=['title'])
df['overview']=df['overview'].fillna(' ')
df['tagline']=df['tagline'].fillna(' ')

In [9]:
df['vote_average']=df['vote_average'].fillna(df['vote_average'].mode()[0])
df['popularity']=df['popularity'].fillna(df['popularity'].mode()[0])

In [10]:
df.isnull().sum()

title           0
genres          0
overview        0
tagline         0
vote_average    0
popularity      0
dtype: int64

In [11]:
df['genres'][1]

"[{'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 10751, 'name': 'Family'}]"

In [12]:
import ast
df['genres']=df['genres'].apply(lambda x:" ".join(i['name']  for i in ast.literal_eval(x)))

In [13]:
df.head()

,title,genres,overview,tagline,vote_average,popularity
0,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",,7.7,21.946943
1,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [14]:
df['tags']=df['genres']+" "+df['overview']+" "+df['tagline']

In [15]:
df.head()

,title,genres,overview,tagline,vote_average,popularity,tags
0,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",,7.7,21.946943,"Animation Comedy Family Led by Woody, Andy's t..."
1,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,6.9,17.015539,Adventure Fantasy Family When siblings Judy an...
2,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,Romance Comedy A family wedding reignites the ...
3,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,6.1,3.859495,"Comedy Drama Romance Cheated on, mistreated an..."
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,5.7,8.387519,Comedy Just when George Banks has recovered fr...

In [16]:
import nltk 
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re
from tqdm import tqdm
tqdm.pandas()

In [17]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [18]:
stop_word=set(stopwords.words('english'))
lemmatizer=WordNetLemmatizer()

In [19]:
def preprocess_text(text):
    text=text.lower()
    text=re.sub(r'[^a-zA-Z]',' ',text)
    words=text.split()
    words=[word for word in words if word not in stop_word]
    words=[lemmatizer.lemmatize(word) for word in words ]
    return " ".join(words)

In [20]:
df['tags']=df['tags'].progress_apply(preprocess_text)

100%|██████████| 45447/45447 [00:11<00:00, 4027.09it/s]

In [21]:
df=df.reset_index(drop=True)

In [22]:
indices = pd.Series(df.index, index=df["title"]).drop_duplicates()

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [24]:
tfidf=TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words='english')

In [25]:
tfidf_matrix = tfidf.fit_transform(tqdm(df['tags']))

100%|██████████| 45447/45447 [00:03<00:00, 14984.92it/s]

In [26]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1582174 stored elements and shape (45447, 50000)>

In [27]:
from sklearn.metrics.pairwise import cosine_similarity

In [28]:
def recommned(title,n=10):
    if title not in indices:
        return ['Movie not found']
    idx=indices[title]
    sim_score=cosine_similarity(tfidf_matrix[idx],tfidf_matrix).flatten()
    similar_idx=sim_score.argsort()[::-1][1:n+1]
    return df['title'].iloc[similar_idx]

In [29]:
recommned('Jumanji')

35576                  Aschenputtel
9500                      Word Wars
21625                  Table No. 21
37429            The Ouija Exorcism
13707                    Rhinoceros
34757    Doctor Who: Last Christmas
19784         Indie Game: The Movie
30234               The Games Maker
35493                      The Mend
44357             Liar Game: Reborn
Name: title, dtype: object

In [30]:
import pickle 
pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))
pickle.dump(indices,open('indices.pkl','wb'))
df.to_pickle('df.pkl')
pickle.dump(tfidf,open('tfidf.pkl','wb'))